[document]
company-name = ""
brand-logo-scale = "100"
disable-smart-templates = "false"

[settings]
drawerPosition = 1.0
textViewCursorLength = 0
textViewCursorLocation = 3762
textViewScrollPosition = 3765


[overrides]